-- Tabla de deportes
CREATE TABLE IF NOT EXISTS Deporte (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL UNIQUE,
    Icon VARCHAR(200),
    BgClass VARCHAR(100),
    TextClass VARCHAR(100)
);

-- Tabla de tipos de usuario
CREATE TABLE IF NOT EXISTS TipoUsuario (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(20) NOT NULL UNIQUE
);

-- Tabla de usuarios
CREATE TABLE IF NOT EXISTS Usuario (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Auth0Id VARCHAR(128) UNIQUE NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Telefono VARCHAR(20),
    PasswordHash VARCHAR(255),
    DebeCambiarPassword BOOLEAN DEFAULT FALSE,
    TipoUsuarioId INTEGER NOT NULL REFERENCES TipoUsuario(Id),
    FechaRegistro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de ciudades
CREATE TABLE IF NOT EXISTS Ciudad (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL UNIQUE
);

-- Tabla de complejos (con nuevas columnas)
CREATE TABLE IF NOT EXISTS Complejo (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Direccion VARCHAR(200),
    CiudadId INTEGER NOT NULL REFERENCES Ciudad(Id),
    DuenoId INTEGER NOT NULL REFERENCES Usuario(Id),
    DeporteId BIGINT REFERENCES Deporte(Id) ON DELETE SET NULL,
    Precio DECIMAL(10,2),
    Imagen TEXT,
    Categoria VARCHAR(100),
    DeportePillBg VARCHAR(100),
    DeportePillText VARCHAR(100),
    Estado BOOLEAN DEFAULT TRUE,
    FechaCreacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MaxDiasDisponiblesReserva INTEGER
);

-- Tabla de tipos de cancha
CREATE TABLE IF NOT EXISTS TipoCancha (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL UNIQUE
);

-- Tabla de canchas
CREATE TABLE IF NOT EXISTS Cancha (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ComplejoId INTEGER NOT NULL REFERENCES Complejo(Id),
    TipoCanchaId INTEGER NOT NULL REFERENCES TipoCancha(Id),
    Nombre VARCHAR(100) NOT NULL,
    PrecioHora DECIMAL(10,2),
    Estado BOOLEAN DEFAULT TRUE,
    Descripcion TEXT
);

-- Tabla de reservas
CREATE TABLE IF NOT EXISTS Reserva (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UsuarioId INTEGER NOT NULL REFERENCES Usuario(Id),
    ComplejoId INTEGER NOT NULL REFERENCES Complejo(Id),
    CanchaId INTEGER NOT NULL REFERENCES Cancha(Id),
    Fecha TIMESTAMP NOT NULL,
    FechaFin TIMESTAMP NOT NULL,
    MedioPago VARCHAR(50),
    MontoTotal DECIMAL(10,2),
    EstadoPago VARCHAR(20) DEFAULT 'pendiente' CHECK (EstadoPago IN ('pendiente', 'pagado', 'cancelado')),
    Confirmada BOOLEAN DEFAULT FALSE,
    FechaReserva TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS horario_cancha
(
    id BIGSERIAL PRIMARY KEY,
    canchaid BIGINT NOT NULL,
    dia_semana INTEGER NOT NULL,          -- 1=lunes ... 7=domingo
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    disponible BOOLEAN DEFAULT true,
    
    CONSTRAINT horario_cancha_canchaid_fkey FOREIGN KEY (canchaid)
        REFERENCES public.cancha (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    -- Evita duplicados en la misma cancha
    CONSTRAINT horario_cancha_unico UNIQUE (canchaid, dia_semana, hora_inicio, hora_fin),

    -- Evita rangos invertidos
    CONSTRAINT horario_cancha_horario_valido CHECK (hora_fin > hora_inicio)
);
