-- Tabla de tipos de usuario
CREATE TABLE IF NOT EXISTS TipoUsuario (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(20) NOT NULL UNIQUE
);

-- Tabla de usuarios
CREATE TABLE IF NOT EXISTS Usuario (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Auth0Id VARCHAR(128) UNIQUE NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Telefono VARCHAR(20),
    TipoUsuarioId INTEGER NOT NULL REFERENCES TipoUsuario(Id),
    FechaRegistro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de ciudades
CREATE TABLE IF NOT EXISTS Ciudad (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL UNIQUE
);

-- Tabla de complejos
CREATE TABLE IF NOT EXISTS Complejo (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Direccion VARCHAR(200),
    CiudadId INTEGER NOT NULL REFERENCES Ciudad(Id),
    DuenoId INTEGER NOT NULL REFERENCES Usuario(Id),
    Precio DECIMAL(10,2),
    Imagen TEXT,
    Estado BOOLEAN DEFAULT TRUE,
    FechaCreacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de tipos de cancha
CREATE TABLE IF NOT EXISTS TipoCancha (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL UNIQUE
);

-- Tabla de canchas
CREATE TABLE IF NOT EXISTS Cancha (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ComplejoId INTEGER NOT NULL REFERENCES Complejo(Id),
    TipoCanchaId INTEGER NOT NULL REFERENCES TipoCancha(Id),
    Nombre VARCHAR(100) NOT NULL,
    PrecioHora DECIMAL(10,2),
    Estado BOOLEAN DEFAULT TRUE,
    Descripcion TEXT
);

-- Tabla de reservas
CREATE TABLE IF NOT EXISTS Reserva (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UsuarioId INTEGER NOT NULL REFERENCES Usuario(Id),
    ComplejoId INTEGER NOT NULL REFERENCES Complejo(Id),
    CanchaId INTEGER NOT NULL REFERENCES Cancha(Id),
    Fecha TIMESTAMP NOT NULL,
    FechaFin TIMESTAMP NOT NULL,
    MedioPago VARCHAR(50),
    MontoTotal DECIMAL(10,2),
    EstadoPago VARCHAR(20) DEFAULT 'pendiente' CHECK (EstadoPago IN ('pendiente', 'pagado', 'cancelado')),
    Confirmada BOOLEAN DEFAULT FALSE,
    FechaReserva TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insertar tipos de usuario básicos (solo si no existen)
INSERT INTO TipoUsuario (Nombre) 
SELECT 'Cliente' WHERE NOT EXISTS (SELECT 1 FROM TipoUsuario WHERE Nombre = 'Cliente')
UNION ALL
SELECT 'Dueno' WHERE NOT EXISTS (SELECT 1 FROM TipoUsuario WHERE Nombre = 'Dueno')
UNION ALL
SELECT 'Admin' WHERE NOT EXISTS (SELECT 1 FROM TipoUsuario WHERE Nombre = 'Admin');

-- Insertar tipos de cancha básicos (solo si no existen)
INSERT INTO TipoCancha (Nombre) 
SELECT 'Futbol 5' WHERE NOT EXISTS (SELECT 1 FROM TipoCancha WHERE Nombre = 'Futbol 5')
UNION ALL
SELECT 'Futbol 7' WHERE NOT EXISTS (SELECT 1 FROM TipoCancha WHERE Nombre = 'Futbol 7')
UNION ALL
SELECT 'Futbol 11' WHERE NOT EXISTS (SELECT 1 FROM TipoCancha WHERE Nombre = 'Futbol 11')
UNION ALL
SELECT 'Padel' WHERE NOT EXISTS (SELECT 1 FROM TipoCancha WHERE Nombre = 'Padel');
